name: smooth
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

# https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool
dependency_overrides:
  sky_engine:
    path: /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
