name: smooth
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.4.0-29.0.pre.111"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  image: ^3.2.0
  lint: ^1.10.0
  mockito: ^5.3.2

# https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool
dependency_overrides:
  sky_engine:
    path: /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
