name: CI

on:
  push: {}
  pull_request: {}

jobs:
  generation:
    name: Generation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v4

      - run: python -m generation --ci
        working-directory: ./scripts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check nothing changes in blob
        run: git diff --exit-code
        working-directory: ./blob

      - name: Check nothing changes
        run: git diff --exit-code
        working-directory: .
