name: Test deployment

on:
  pull_request:
    branches:
      - master
    paths:
      - 'website/**'
      - 'blob'
      - '.github/workflows/**'

# ref https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website
      - name: Test build website
        run: yarn build
        working-directory: ./website

